### ISSUE TITLE
Issue With shared with "ORGANIZATION_DEPARTMENTS" posts/polls

### ISSUE THREAD

**Issue by yatishTrootech** [rewardz/Feeds#122]
If posts/polls have `shared_with = ORGANIZATION_DEPARTMENTS`
1. It should only be visible to the department which is selected for the same organization
2. If another (affiliated ORG) department is selected then it should only be seen by another org-selected department
3. It should be visible to the creator 

Also check if the post is showing in the list then it should perform all things update/like/etc

Linked more details in fail cases in this [card](https://github.com/rewardz/skor/issues/4569)

**Comment by qanaveen1111** [comment]
- [ ] This changes is for Nuhs App. @yatishTrootech  Mcd(Happi app ) dosent have custom options for post and polls .

@suryaiiit

**Comment by suryaiiit** [comment]
Can I say Multi-Org Post is all good on NUHS?
I understand Polls is not built yet.

**Comment by suryaiiit** [comment]
We should support Polls as well for multi-orgs

**Comment by yatishTrootech** [comment]
Issue1: https://github.com/rewardz/Feeds/issues/141#issuecomment-1521217753

**Comment by yatishTrootech** [comment]
Issue1: https://github.com/rewardz/Feeds/issues/141#issuecomment-1521217753

**Comment by qanaveen1111** [comment]
# Pass

Date -28-4-23
Server-prashant.skordev.com
Users [-user1@nuhs.ed.sg]

Poll to Custom-->This poll we can give to only selected departments in both parent and child Org admin can select any multiple depts that he want to poll.

- [ ]  Expected behaviour :- Org-parent (Poll type -Custom)-Created poll form [[user1@nuhs.edu.sg](mailto:user1@nuhs.edu.sg)] to parent Org (dept pharmacy) login with Parent Org Diagnostics dept poll is not showing , login with pharmacy dept poll is showing and login with child Org users poll is not showing.
Actual : Poll is showing in both departments
- [ ] Expected behaviour :-ORG-child (poll type -Custom)-Created poll from [[admin@test8.com](mailto:admin@test8.com)] to child Org (dept cardic ) login with child Org clinical dept user poll is not showing and login with child org cardiac user poll is showing and login with parent Org user poll is not showing
@yatishTrootech @SteffiVinod5
